<?php

namespace NS;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-10 at 11:27:43.
 */
class NestedSetNodeTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var NestedSetNode
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new NestedSetNode;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers NS\NestedSetNode::fromArray
   * @todo   Implement testFromArray().
   */
  public function testFromArray() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSetNode::isRoot
   * @todo   Implement testIsRoot().
   */
  public function testIsRoot() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSetNode::getKey
   * @todo   Implement testGetKey().
   */
  public function testGetKey() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSetNode::getTreeId
   * @todo   Implement testGetTreeId().
   */
  public function testGetTreeId() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSetNode::getDescendants
   * @todo   Implement testGetDescendants().
   */
  public function testGetDescendants() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSetNode::getChildren
   * @todo   Implement testGetChildren().
   */
  public function testGetChildren() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSetNode::addChild
   * @todo   Implement testAddChild().
   */
  public function testAddChild() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSetNode::addSibling
   * @todo   Implement testAddSibling().
   */
  public function testAddSibling() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSetNode::toArray
   * @todo   Implement testToArray().
   */
  public function testToArray() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

}
