<?php

namespace NS;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-10 at 12:00:35.
 */
class NestedSetTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var NestedSet
   */
  protected $object;
  private $dsn = 'mysql:host=localhost;dbname=tree;port=3306';
  private $user = 'root';
  private $password = '';

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $pdo = new \PDO($this->dsn, $this->user, $this->password);
    $sql = "
DROP TABLE IF EXISTS `tree_test`;
CREATE TABLE IF NOT EXISTS `tree_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL,
  `lft` int(11) NOT NULL,
  `rgt` int(11) NOT NULL,
  `parent_id` int(11) DEFAULT NULL
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=11 ;

INSERT INTO `tree_test` (`id`, `name`, `lft`, `rgt`, `parent_id`) VALUES
(1, 'root 1', 1, 20, NULL),
(2, 'child 1.1', 2, 9, 1),
(3, 'child 1.1.1', 3, 4, 2),
(4, 'child 1.1.2', 5, 6, 2),
(5, 'child 1.1.3', 7, 8, 2),
(6, 'child 1.2', 10, 19, 1),
(7, 'child 1.2.1', 11, 14, 6),
(8, 'child 1.2.1.1', 12, 13, 7),
(9, 'child 1.2.2', 15, 16, 6),
(10, 'child 1.2.3', 17, 18, 6);
";
    $pdo->exec($sql);

    $this->object = new NestedSet($pdo, 'tree_test', 'id', 'parent_id', null, 'lft', 'rgt');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

 
  /**
   * @covers NS\NestedSet::quoteIdent
   * @todo   Implement testQuoteIdent().
   */
  public function testQuoteIdent() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getParent
   * @todo   Implement testGetParent().
   */
  public function testGetParent() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getDescendants
   * @todo   Implement testGetDescendants().
   */
  public function testGetDescendants() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getChildren
   * @todo   Implement testGetChildren().
   */
  public function testGetChildren() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getTreeLeafs
   * @todo   Implement testGetTreeLeafs().
   */
  public function testGetTreeLeafs() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getAncestors
   * @todo   Implement testGetAncestors().
   */
  public function testGetAncestors() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getTree
   * @todo   Implement testGetTree().
   */
  public function testGetTree() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getRoots
   * @todo   Implement testGetRoots().
   */
  public function testGetRoots() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getNodeId
   * @todo   Implement testGetNodeId().
   */
  public function testGetNodeId() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::getNode
   * @todo   Implement testGetNode().
   */
  public function testGetNode() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::createRoot
   * @todo   Implement testCreateRoot().
   */
  public function testCreateRoot() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::createChild
   * @todo   Implement testCreateChild().
   */
  public function testCreateChild() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::countChildren
   * @todo   Implement testCountChildren().
   */
  public function testCountChildren() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::hasChildren
   * @todo   Implement testHasChildren().
   */
  public function testHasChildren() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::createSibling
   * @todo   Implement testCreateSibling().
   */
  public function testCreateSibling() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::deleteNode
   * @todo   Implement testDeleteNode().
   */
  public function testDeleteNode() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::deleteNodeAndChildren
   * @todo   Implement testDeleteNodeAndChildren().
   */
  public function testDeleteNodeAndChildren() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers NS\NestedSet::deleteTree
   * @todo   Implement testDeleteTree().
   */
  public function testDeleteTree() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

}
